"""Add created column

Revision ID: 2b89284b2d1b
Revises: 1c9e816a228c
Create Date: 2019-12-20 22:53:48.114683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b89284b2d1b'
down_revision = '1c9e816a228c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created')
    # ### end Alembic commands ###
