"""Add float amount

Revision ID: e9e3d0a86bc4
Revises: 2b89284b2d1b
Create Date: 2019-12-29 16:33:04.386685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'e9e3d0a86bc4'
down_revision = '2b89284b2d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount_flaot', sa.Float(precision=2, decimal_return_scale=2), nullable=True))
    # ### end Alembic commands ###
    # Data migration. Fill the float column with the numeric column values
    transactions = table(
        "transactions",
        sa.Column("id", sa.Integer()),
        sa.Column("amount", sa.Numeric()),
        sa.Column("amount_flaot", sa.Float()),
    )
    connection = op.get_bind()
    # Get the existing rows
    rows = connection.execute(
        sa.select([transactions.c.id, transactions.c.amount]),
    ).fetchall()

    # Fill the new value for each row
    for rid, amount in rows:
        connection.execute(
            transactions.update().where(transactions.c.id == rid).
            values({"amount_flaot": amount}),
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'amount_flaot')
    # ### end Alembic commands ###
